### ISSUE TITLE
Info on the project

### ISSUE THREAD

**Issue by Docop2** [arxwtf/2023_PiezoPreamp#1]
Hi so from the reading of your post, it look quite an interesting project. Do you might add the schematic to see it ? That can be handy. 
Thanks a lot.

**Comment by arxwtf** [comment]
Hi @Docop2, thank you for your interest! I added [schematics/](https://github.com/arxwtf/2023_PiezoPreamp/tree/main/schematics) folder to the project root. It contains the schematic sheets plotted directly from KiCAD, individually in .png files or all together in one .pdf. 

It's also possible to open the whole project (2023_PiezoPreamp.kicad_pro) in KiCAD v7, which is the best way to view the schematics, as all the individual components also contain description of their purpose, link to datasheet, manufacturer part numbers etc.

I updated the README with the image of the rendered final PCB as well, and added a section about "Known problems" which I'm discovering now while assembling the prototypes :).
